export const RATINGS = ['g', 'pg', 'pg-13', 'r'];
export const LANGUAGES = [
  { name: 'English', key: 'en' },
  { name: 'Spanish', key: 'es' },
  { name: 'Portuguese', key: 'pt' },
  { name: 'Indonesian', key: 'id' },
  { name: 'French', key: 'fr' },
  { name: 'Arabic', key: 'ar' },
  { name: 'Turkish', key: 'tr' },
  { name: 'Thai', key: 'th' },
  { name: 'Vietnamese', key: 'vi' },
  { name: 'German', key: 'de' },
  { name: 'Italian', key: 'it' },
  { name: 'Japanese', key: 'ja' },
  { name: 'Chinese', key: 'zh-TW' },
  { name: 'Russian', key: 'ru' },
  { name: 'Korean', key: 'ko' },
  { name: 'Polish', key: 'pl' },
  { name: 'Dutch', key: 'nl' },
  { name: 'Romanian', key: 'ro' },
  { name: 'Hungarian', key: 'hu' },
  { name: 'Swedish', key: 'sv' },
  { name: 'Czech', key: 'cs' },
  { name: 'Hindi', key: 'hi' },
  { name: 'Bengali', key: 'bn' },
  { name: 'Danish', key: 'da' },
  { name: 'Farsi', key: 'fa' },
  { name: 'Filipino', key: 'tl' },
  { name: 'Finnish', key: 'fi' },
  { name: 'Hebrew', key: 'he' },
  { name: 'Malay', key: 'ms' },
  { name: 'Norwegian', key: 'no' },
  { name: 'Ukrainian', key: 'uk' },
];
